### ISSUE TITLE
amtgwd: couldn't set tunnel veth3 mode to broadcast: Invalid argument

### ISSUE THREAD

**Issue by BugBaron** [GrumpyOldTroll/amt#2]
Hey there,

I am currently trying to test the code on ubuntu following the instructions in testbed-setup/simpler-testbed.txt, and there is an issue when running the amdgwd file.

Whenever I run the file, the error "amtgwd: couldn't set tunnel veth3 mode to broadcast: Invalid argument" always appears. I have traced the error to line 158 of gateway/gw_tun.c, although I believe the issue may be related to a difference in how TUNSETIFF is run or something. 

Here is some information about the system I am running:
Linux version 4.15.0-69-generic (buildd@lgw01-amd64-032) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #78-Ubuntu SMP Wed Nov 6 11:30:24 UTC 2019

I had to change some of the commands in the testbed-setup/simpler-testbed.txt file to get them to run. Namely, I had to change the commands to run each of the compiled files as follows:

sudo ip netns exec mrelay unbuffer /usr/local/bin/amtrelayd -n inet -l inet -c veth1 -s 10.3.3.1 -q1 -d -a "10.3.3.1/32"

sudo ip netns exec mrcv unbuffer /usr/local/bin/amtgwd -a 10.3.3.1 -c veth3 -d

Any idea what might be causing this problem?

**Comment by GrumpyOldTroll** [comment]
Thanks for taking a look at this.  Apologies, I believe the simpler-testbed.txt instructions went out of date, and haven't been updated.

I believe this error message comes from the spot trying to configure the tunnel interface.  This is the interface between amtgwd and the kernel, which IIRC is where the unwrapped data packets are sent so they can be forwarded according to the downstream devices that have joined, and where IGMP reports are received from the kernel:
https://github.com/GrumpyOldTroll/amt/blob/master/gateway/gw_tun.c#L158

I believe the interface passed for -c therefore now has to be a tunnel interface.  The amtgwd behavior at the time of the simpler-testbed.txt writing was to construct a tunnel interface from the amtgwd program, but this was updated so that the tunnel interface should be constructed externally and passed to amtgwd.  IIRC the reason was for a smoother automated start inside a docker container, which is a much more convenient way to run it, for most purposes.  You can see the commands to configure the tunnel interface in the initialization script:
https://github.com/GrumpyOldTroll/amt/blob/master/gateway/docker/run_amtgwd#L66

(Likewise as shown there, the tunnel interface should get an address and network assigned, which is the kernel's IP address and network mask on that interface, and the -s argument should be a different IP address within the same network space, which is the amtgwd interface's IP address on the tunnel.  This behavior was changed with the tunnel interface change, which used to use the -s argument to configure the tunnel interface's network, and then pick an unconfigurable address from inside there for each side of that interface.)

I hope that's helpful and gets you un-stuck, at least.

If you're able to submit a pull request for the instructions there so that they contain commands that work once you have it working, that would be much appreciated, else I'll add it to my list of things to try to fix when I get a chance.  Cheers.

**Comment by BugBaron** [comment]
Yup, that was a big help. Gateway is connecting to the Relay now.

I can submit a pull request for the instructions when I get it working, but still getting a couple issues.

I couldn't get the iperf-ssm library from noushi to compile, so i'm using the iperf from apt with a few different options. However, the server cannot connect with --ssm-host set, so im just using asm for now.

Also, i can get multicast data sending to the mrelay namespace, but it doesn't get forwarded to the tunnel socket. Any idea why this might be the case? The ip route for the tunnel says linkdown, even when the relay is running, so that might be the cause, but traffic is being forwarded to the gateway from mrcv, and the ports are configured pretty much identically.

Cheers.
Edit: nvm i got iperf working as expected, and got data sending through the tunnel. I had the interface of the relay as the relay end of the tunnel, but changing the interface to veth1 seemed to fix the issues. Now iperf on the gateway is not receiving data, even though it is being sent to the IP stack through the tunnel, but I think that is a separate issue.

**Comment by BugBaron** [comment]
Ok, i submitted a pull request for that simpler testbed. Now i'm trying to connect to your docker test stream, but i don't get any relay advertisement in reply. Pinging works fine, so I don't think the path is compromised. I've tried using both the docker container and externally, but no response with either method. Any idea why that is?

**Comment by GrumpyOldTroll** [comment]
Ah, sorry I missed this message, I've been traveling and am way behind...  Try listening from 23.212.185.4->232.1.1.1, port 5001.  That one is up today.

~~~
$ AMT=$(python3 github/libmcrx/driad.py 23.212.185.4) && docker run -d --rm --name amtgw --privileged grumpyoldtroll/amtgw $AMT
71454ee6af7b6263dfdc2fd45fbdefc61b63c810cb88e227792496e7b703a339
$ docker run -it --rm --name rx2 grumpyoldtroll/iperf-ssm:latest --server --udp --bind 232.1.1.1 --source 23.212.185.4  --interval 1 --len 1500 --interface eth0
setting perf ip4 ttl to 1
------------------------------------------------------------
Server listening on UDP port 5001
Binding to local address 232.1.1.1
Joining multicast group  232.1.1.1
Joining multicast group on interface  eth0
Accepting multicast group source  23.212.185.4
Receiving 1500 byte datagrams
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
setting perf ip4 ttl to 1
[  3] local 232.1.1.1 port 5001 connected with 23.212.185.4 port 5001
[ ID] Interval       Transfer     Bandwidth        Jitter   Lost/Total Datagrams
[  3]  0.0- 1.0 sec  0.00 Bytes  0.00 bits/sec   0.000 ms    0/    0 (-nan%)
[  3]  1.0- 2.0 sec   125 Bytes  1.00 Kbits/sec   0.000 ms  406/  407 (1e+02%)
[  3]  2.0- 3.0 sec   125 Bytes  1.00 Kbits/sec   0.007 ms    0/    1 (0%)
[  3]  3.0- 4.0 sec   250 Bytes  2.00 Kbits/sec   0.334 ms    0/    2 (0%)
~~~

I should probably spin back up the source address I had running, or keep the instructions up to date somehow.  They go up and down a little bit from time to time and I don't always keep it current, my bad.

**Comment by BugBaron** [comment]
Hey, i didn't get a chance to test that sorry, is there any chance you could spin that up again at some point?
Also, I think to get DRIAD working, I might need to connect to a different DNS server. Which one is that source address registered on?
Cheers

**Comment by GrumpyOldTroll** [comment]
That's still operational right now, the above commands should work.

I heard that bind 9.11 wasn't working with generic RRTypes, but bind 9.14 has it fixed.  If your DNS server doesn't work, I'd be interested to know which one it is, but the big public ones seem to all have it:

~~~
$ dig @8.8.8.8 +short -t TYPE260 4.185.212.23.in-addr.arpa
4.v4.driad.akastream2.com.
\# 22 1003047234763403616D7406616B61646E73036E6574
$ dig @1.1.1.1 +short -t TYPE260 4.185.212.23.in-addr.arpa
4.v4.driad.akastream2.com.
\# 22 1003047234763403616D7406616B61646E73036E6574
$ dig @9.9.9.9 +short -t TYPE260 4.185.212.23.in-addr.arpa
4.v4.driad.akastream2.com.
\# 22 1003047234763403616D7406616B61646E73036E6574
$ dig @208.67.222.222 +short -t TYPE260 4.185.212.23.in-addr.arpa
4.v4.driad.akastream2.com.
\# 22 1003047234763403616D7406616B61646E73036E6574
$ dig @64.6.64.6 +short -t TYPE260 4.185.212.23.in-addr.arpa
4.v4.driad.akastream2.com.
\# 22 1003047234763403616D7406616B61646E73036E6574
$ dig @185.228.168.9 +short -t TYPE260 4.185.212.23.in-addr.arpa
4.v4.driad.akastream2.com.
\# 22 1003047234763403616D7406616B61646E73036E6574
$ dig @176.103.130.130 +short -t TYPE260 4.185.212.23.in-addr.arpa
4.v4.driad.akastream2.com.
\# 22 1003047234763403616D7406616B61646E73036E6574
~~~

I'm not sure offhand what the authoritative one is but it shouldn't matter, if you can use one of those, or if your recursive default one supports generic RRs.  But if necessary it should work ok to just hack '@8.8.8.8' into the command line call:

https://github.com/GrumpyOldTroll/libmcrx/blob/master/driad.py#L54

HTH

**Comment by BugBaron** [comment]
Yup, that seemed to do the trick. Looks like the local DNS server is getting a bit confused. Had to change both dig commands in driad.py.
I was trying to connect to the relay at 23.202.36.4 earlier, but I guess you didn't have that one running? Regardless, the driad one works fine. Cheers.

**Comment by GrumpyOldTroll** [comment]
Hmm, I should look into that one, thanks.  23.202.36.4 should be running a
discovery broker on anycast, but I think you're right that it's down.
Gotta make something to alert me when that happens, sorry about that...
