### ISSUE TITLE
AMT Relay tunnel interface?

### ISSUE THREAD

**Issue by BugBaron** [GrumpyOldTroll/amt#4]
Hey there,

I was just considering making the relay use a tunnel interface for our purposes, and I thought I might see if you knew what parts of the code need refactoring for that purpose? If not, I'll just keep looking around on my own.

Cheers

**Comment by GrumpyOldTroll** [comment]
Hiya,

I'd first recommend using amtrelayd (https://github.com/GrumpyOldTroll/amtrelayd) instead of amt/relay.  I'm planning to deprecate that in this codebase, since it's moved and the build is cleaner there.  I think the code is roughly the same, with perhaps an extra fix or 2 in amtrelayd.

I think if you want the data to use a tunnel interface, I'd expect that already to work (though I haven't tried it recently--did you see something different?).  Unlike the gateway, where a tunnel interface is sort of required for forwarding the native multicast from the executable into the kernel's routing engine, the relay only has to receive the native multicast and then generate regular UDP, so any kind of interface should work ok, as long as the native multicast arrives at that interface.

So for example, I often run a relay on the same machine as my sending application, and my setup looks like:

~~~
/sbin/ip link add dev dum0 type veth peer name dum1
sleep 1
/sbin/ip addr add ${MY_SOURCE_IP}/24 dev dum1
/sbin/ip link set up dev dum1
/sbin/ip link set up dev dum0
/sbin/ip route add 232.0.0.0/8 dev dum1
/sbin/ethtool --offload dum1 tx off
~~~

Then my amtrelayd.conf looks like this:

~~~
RelayFamily inet
TunnelFamily inet
RelayAddr ${MY_PUBLIC_IP}
DiscoveryAddr ${MY_NAT_IP}
TunnelAddr ${MY_SOURCE_IP}
NatMode 1
DataInterface dum0
#DataPort 5001
DataPort all
~~~

This runs on aws, where ${MY_NAT_IP} is the IP of my interface as seen by the ec2 instance, ${MY_PUBLIC_IP} is the public IP of the ec2 instance (which is translated to ${MY_NAT_IP} before it reaches the instance), and ${MY_SOURCE_IP} is the source ip from the dum1 interface, where the sender is sending traffic.

I hope that's helpful, and I think (but haven't checked) that if you instead created a tunnel interface, set up the routing properly, and listened on the tunnel interface, it would work without special hacking.  However, if you do need special hacking, I assume the entry point would be something regarding the DataInterface value, which basically sets cap_iface_index (which then gets passed to the join), so you'd want to look in those spots:

Where configured:
https://github.com/GrumpyOldTroll/amtrelayd/blob/master/src/config.c#L70

Where joining and leaving
 * membership_join:
    <https://github.com/GrumpyOldTroll/amtrelayd/blob/master/src/tree.c#L277>
 * membership_leave:
    <https://github.com/GrumpyOldTroll/amtrelayd/blob/master/src/tree.c#L159>

There might also be something extra necessary for raw sockets if you need to do something along these lines, the likely candidates being:

 * data_group_change:
    <https://github.com/GrumpyOldTroll/amtrelayd/blob/master/src/recv.c#L2497>
 * relay_raw_socket_init:
    <https://github.com/GrumpyOldTroll/amtrelayd/blob/master/src/recv.c#L2935>

HTH.

**Comment by BugBaron** [comment]
I will probably keep the relay from this repo, since we already have a system for building with autotools.

We don't let IGMP or MLD run on our loopback devices i think, which is what we are really looking to use. So I think making a tunnel interface is the best option.

Thanks for the help.
